# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='palyed_time',
            new_name='played_time',
        ),
    ]
